### ISSUE TITLE
[Suqqestion] Publish to open-vsx.org

### ISSUE THREAD

**Issue by GameBurrow** [fuljo/language-omsi#6]
Suggesting for this to be published on open-vsx.org also, so it could easily be used with vscodium also
https://github.com/VSCodium/vscodium/blob/master/docs/index.md#extensions--marketplace

**Comment by fuljo** [comment]
Hi there,
thanks for the suggestion.
I've just published the extension to Open VSX: https://open-vsx.org/extension/fuljo/language-omsi

As of now, I've claimed the `fuljo` namespace and I'm waiting for the ownership to be accepted.
